id: AAC195C20
title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind Kīla
  Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
type: translation
pechas:
- I2EE4C54B
- I4F6D788B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:56.456051
  last_modified_at: 2023-01-04 11:52:56.456055
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I2EE4C54B/6952: DDE4
  I4F6D788B/E7DE: DDE4
